#!/bin/bash

PREFIX=$(cat <<EOF
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 20010904//EN"
 "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg version="1.0" xmlns="http://www.w3.org/2000/svg"
 width="2480.000000pt" height="3508.000000pt" viewBox="0 0 2480.000000 3508.000000"
 preserveAspectRatio="xMidYMid meet">
<metadata>
Created by potrace 1.15, written by Peter Selinger 2001-2017
</metadata>
EOF
)

SUFFIX=$( cat <<EOF
</svg>
EOF
)

if [ -z "$1" ]; then
    exit
fi

input_file=$1
base=$(basename "$input_file" .bmp)
output_file=${base}.svg

if [ "$2" == "-colors" ]; then
    red_file=${base}_red.bmp
    blue_file=${base}_blue.bmp
    green_file=${base}_green.bmp
    black_file=${base}_black.bmp

    red_svg=${base}_red.svg
    blue_svg=${base}_blue.svg
    green_svg=${base}_green.svg
    black_svg=${base}_black.svg

    convert "$input_file" -fill white +opaque "#ff0000" "$red_file"
    convert "$input_file" -fill white +opaque "#0000ff" "$blue_file"
    convert "$input_file" -fill white +opaque "#00ff00" "$green_file"
    convert "$input_file" -fill white +opaque "#000000" "$black_file"

    potrace -s --color "#ff0000" -o "$red_svg" "$red_file"
    potrace -s --color "#ff0000" -o "$blue_svg" "$blue_file"
    potrace -s --color "#00ff00" -o "$green_svg" "$green_file"
    potrace -s --color "#000000" -o "$black_svg" "$black_file"

    echo "$PREFIX" > "$output_file"
    ./xpath.py "$red_svg" "//p:g" >> "$output_file"
    ./xpath.py "$green_svg" "//p:g" >> "$output_file"
    ./xpath.py "$blue_svg" "//p:g" >> "$output_file"
    ./xpath.py "$black_svg" "//p:g" >> "$output_file"
    echo "$SUFFIX" >> "$output_file"

    rm "$red_file" "$red_svg" "$green_file" "$green_svg" "$blue_file" "$blue_svg" "$black_file" "$black_svg"
else
    potrace -s -o "$output_file" "$input_file"
fi
